CREATE TABLE SAMPLE_USER (
    USER_ID         VARCHAR(50)     NOT NULL PRIMARY KEY,
    USER_NAME       VARCHAR(100)    NOT NULL,
    USER_PW         VARCHAR(255)    NOT NULL,
    USER_AUTH_TYPE  VARCHAR(20)     NOT NULL
);

CREATE TABLE SAMPLE_BOARD (
    BOARD_SEQ       INT             NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE           VARCHAR(50)     NOT NULL,
    CONTENT         TEXT            NOT NULL,
    CREATE_USER_ID  VARCHAR(50)     NOT NULL,
    CREATE_DT       TIMESTAMP       NOT NULL,
    UPDATE_USER_ID  VARCHAR(50)     NOT NULL,
    UPDATE_DT       TIMESTAMP       NOT NULL
);
